cache: cargo
dist: trusty
language: rust
# NOTE This is default but can be override on a target by target basis in the "matrix" below
rust: nightly
services: docker
sudo: required

env:
  global:
    - TARGET=thumbv7m-none-eabi

matrix:
  include:
    # FIXME(rust-lang/rust#38406) uncomment this when rust-lang/rust#38411
    # reaches nightly
    # - env: TARGET=thumbv6m-none-eabi
    - env: TARGET=thumbv7em-none-eabi
    - env: TARGET=thumbv7em-none-eabihf

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $TRAVIS_RUST_VERSION
  - source ~/.cargo/env
  - rustup component add rust-src

script:
  - cargo generate-lockfile
  - if [[ $TRAVIS_OS_NAME = linux ]]; then
      sh ci/run-docker.sh $TARGET || exit 1;
    else
      sh ci/run.sh || exit 1;
    fi;
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - auto
    - try
